# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUI(object):
    def setupUi(self, JarvisUI):
        JarvisUI.setObjectName("JarvisUI")
        JarvisUI.resize(1913, 1044)
        self.JarvisUi = QtWidgets.QWidget(JarvisUI)
        self.JarvisUi.setObjectName("JarvisUi")
        self.Bg_1 = QtWidgets.QLabel(self.JarvisUi)
        self.Bg_1.setGeometry(QtCore.QRect(-30, -10, 2001, 1101))
        self.Bg_1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Bg_1.setText("")
        self.Bg_1.setPixmap(QtGui.QPixmap("D:/jarvisGif/B.G/Black_Template.jpg"))
        self.Bg_1.setScaledContents(True)
        self.Bg_1.setObjectName("Bg_1")
        self.Bg_3 = QtWidgets.QLabel(self.JarvisUi)
        self.Bg_3.setGeometry(QtCore.QRect(570, 10, 821, 581))
        self.Bg_3.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.Bg_3.setText("")
        self.Bg_3.setScaledContents(True)
        self.Bg_3.setObjectName("Bg_3")
        self.Gif_1 = QtWidgets.QLabel(self.JarvisUi)
        self.Gif_1.setGeometry(QtCore.QRect(10, 10, 471, 661))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("D:/jarvisGif/ExtraGui/B.G_Template_1.gif"))
        self.Gif_1.setScaledContents(True)
        self.Gif_1.setObjectName("Gif_1")
        self.Gif_2 = QtWidgets.QLabel(self.JarvisUi)
        self.Gif_2.setGeometry(QtCore.QRect(490, -50, 1111, 711))
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("D:/jarvisGif/ExtraGui/live.gif"))
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("Gif_2")
        self.Bg_4 = QtWidgets.QLabel(self.JarvisUi)
        self.Bg_4.setGeometry(QtCore.QRect(0, 740, 361, 231))
        self.Bg_4.setText("")
        self.Bg_4.setPixmap(QtGui.QPixmap("D:/jarvisGif/B.G/gyhf.jpg"))
        self.Bg_4.setScaledContents(True)
        self.Bg_4.setObjectName("Bg_4")

        self.Text_date = QtWidgets.QLabel(self.JarvisUi)
        self.Text_date.setGeometry(QtCore.QRect(50, 890, 261, 51))
        self.Text_date.setStyleSheet("background-color: Transparent;\n"
                                     "border-radius: none;\n"
                                     "color: rgb(0, 255, 255);\n"
                                     "font-size: 25px;")
        self.Text_date.setText("")
        self.Text_date.setObjectName("Text_date")

        self.Text_time = QtWidgets.QLabel(self.JarvisUi)
        self.Text_time.setGeometry(QtCore.QRect(50, 770, 261, 51))
        self.Text_time.setStyleSheet("background-color: Transparent;\n"
                                     "border-radius: none;\n"
                                     "color: rgb(0, 255, 255);\n"
                                     "font-size: 25px;")
        self.Text_time.setText("")
        self.Text_time.setObjectName("Text_time")

        self.StartButton = QtWidgets.QPushButton(self.JarvisUi)
        self.StartButton.setGeometry(QtCore.QRect(1290, 900, 231, 41))
        self.StartButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StartButton.setStyleSheet("background-color: Transparent;\n"
                                       "border-radius: none;")
        self.StartButton.setObjectName("StartButton")
        self.Start_bg = QtWidgets.QLabel(self.JarvisUi)
        self.Start_bg.setGeometry(QtCore.QRect(1260, 860, 291, 111))
        self.Start_bg.setText("")
        self.Start_bg.setPixmap(QtGui.QPixmap("D:/jarvisGif/Buttons/Start.png"))
        self.Start_bg.setScaledContents(True)
        self.Start_bg.setObjectName("Start_bg")
        self.Quit_bg = QtWidgets.QLabel(self.JarvisUi)
        self.Quit_bg.setGeometry(QtCore.QRect(1590, 870, 291, 101))
        self.Quit_bg.setText("")
        self.Quit_bg.setPixmap(QtGui.QPixmap("D:/jarvisGif/Buttons/Quit.png"))
        self.Quit_bg.setScaledContents(True)
        self.Quit_bg.setObjectName("Quit_bg")
        self.QuitButton = QtWidgets.QPushButton(self.JarvisUi)
        self.QuitButton.setGeometry(QtCore.QRect(1620, 900, 231, 41))
        self.QuitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QuitButton.setStyleSheet("background-color: Transparent;\n"
                                      "border-radius: none;")
        self.QuitButton.setObjectName("QuitButton")
        self.Youtube_Botton = QtWidgets.QPushButton(self.JarvisUi)
        self.Youtube_Botton.setGeometry(QtCore.QRect(580, 890, 101, 51))
        self.Youtube_Botton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Youtube_Botton.setStyleSheet("background-color: Transparent;\n"
                                          "border-radius: none;")
        self.Youtube_Botton.setText("")
        self.Youtube_Botton.setObjectName("Youtube_Botton")
        self.Youtube_2 = QtWidgets.QLabel(self.JarvisUi)
        self.Youtube_2.setGeometry(QtCore.QRect(580, 890, 111, 61))
        self.Youtube_2.setText("")
        self.Youtube_2.setPixmap(QtGui.QPixmap(
            "../Users/user/OneDrive/Pictures/Saved Pictures/youtube-play-button-file-youtube-play-buttom-icon-svg-wikimedia-commons-8.png"))
        self.Youtube_2.setScaledContents(True)
        self.Youtube_2.setObjectName("Youtube_2")
        self.Whatsapp = QtWidgets.QLabel(self.JarvisUi)
        self.Whatsapp.setGeometry(QtCore.QRect(740, 880, 111, 81))
        self.Whatsapp.setText("")
        self.Whatsapp.setPixmap(QtGui.QPixmap("../Users/user/OneDrive/Pictures/Saved Pictures/WhatsApp_icon.png.webp"))
        self.Whatsapp.setScaledContents(True)
        self.Whatsapp.setObjectName("Whatsapp")
        self.chrome = QtWidgets.QLabel(self.JarvisUi)
        self.chrome.setGeometry(QtCore.QRect(890, 880, 91, 81))
        self.chrome.setText("")
        self.chrome.setPixmap(
            QtGui.QPixmap("../Users/user/OneDrive/Pictures/Saved Pictures/Google_Chrome_icon_(2011).png"))
        self.chrome.setScaledContents(True)
        self.chrome.setObjectName("chrome")
        self.Facebook = QtWidgets.QLabel(self.JarvisUi)
        self.Facebook.setGeometry(QtCore.QRect(1040, 890, 91, 61))
        self.Facebook.setText("")
        self.Facebook.setPixmap(QtGui.QPixmap("../Users/user/OneDrive/Pictures/Saved Pictures/download (1).png"))
        self.Facebook.setScaledContents(True)
        self.Facebook.setObjectName("Facebook")
        self.Whatsapp_Botton = QtWidgets.QPushButton(self.JarvisUi)
        self.Whatsapp_Botton.setGeometry(QtCore.QRect(760, 890, 71, 61))
        self.Whatsapp_Botton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Whatsapp_Botton.setStyleSheet("background-color: Transparent;\n"
                                           "border-radius: none;")
        self.Whatsapp_Botton.setText("")
        self.Whatsapp_Botton.setObjectName("Whatsapp_Botton")
        self.Chrome_Botton = QtWidgets.QPushButton(self.JarvisUi)
        self.Chrome_Botton.setGeometry(QtCore.QRect(900, 890, 71, 61))
        self.Chrome_Botton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Chrome_Botton.setStyleSheet("background-color: Transparent;\n"
                                         "border-radius: none;")
        self.Chrome_Botton.setText("")
        self.Chrome_Botton.setObjectName("Chrome_Botton")
        self.Facebook_Botton = QtWidgets.QPushButton(self.JarvisUi)
        self.Facebook_Botton.setGeometry(QtCore.QRect(1040, 890, 91, 61))
        self.Facebook_Botton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Facebook_Botton.setStyleSheet("background-color: Transparent;\n"
                                           "border-radius: none;")
        self.Facebook_Botton.setText("")
        self.Facebook_Botton.setObjectName("Facebook_Botton")
        self.Gif_3 = QtWidgets.QLabel(self.JarvisUi)
        self.Gif_3.setGeometry(QtCore.QRect(1500, 20, 471, 341))
        self.Gif_3.setStyleSheet("background-color: Transparent;\n"
                                 "border-radius: none;")
        self.Gif_3.setText("")
        self.Gif_3.setPixmap(QtGui.QPixmap("D:/jarvisGif/ExtraGui/Earth.gif"))
        self.Gif_3.setScaledContents(True)
        self.Gif_3.setObjectName("Gif_3")
        self.Gif_5 = QtWidgets.QLabel(self.JarvisUi)
        self.Gif_5.setGeometry(QtCore.QRect(580, 600, 981, 171))
        self.Gif_5.setStyleSheet("background-color: Transparent;")
        self.Gif_5.setText("")
        self.Gif_5.setPixmap(QtGui.QPixmap("../Users/user/OneDrive/Pictures/Saved Pictures/ios_9.gif"))
        self.Gif_5.setScaledContents(True)
        self.Gif_5.setObjectName("Gif_5")
        self.Gif_4 = QtWidgets.QLabel(self.JarvisUi)
        self.Gif_4.setGeometry(QtCore.QRect(1500, 390, 481, 271))
        self.Gif_4.setStyleSheet("background-color: Transparent;\n"
                                 "border-radius: none;")
        self.Gif_4.setText("")
        self.Gif_4.setPixmap(QtGui.QPixmap("D:/jarvisGif/VoiceReg/jarvis_jj.gif"))
        self.Gif_4.setScaledContents(True)
        self.Gif_4.setObjectName("Gif_4")
        self.Bg_1.raise_()
        self.Bg_3.raise_()
        self.Gif_1.raise_()
        self.Bg_4.raise_()
        self.Text_date.raise_()
        self.Text_time.raise_()
        self.Start_bg.raise_()
        self.Quit_bg.raise_()
        self.StartButton.raise_()
        self.QuitButton.raise_()
        self.Youtube_2.raise_()
        self.Whatsapp.raise_()
        self.chrome.raise_()
        self.Facebook.raise_()
        self.Youtube_Botton.raise_()
        self.Whatsapp_Botton.raise_()
        self.Chrome_Botton.raise_()
        self.Facebook_Botton.raise_()
        self.Gif_3.raise_()
        self.Gif_2.raise_()
        self.Gif_5.raise_()
        self.Gif_4.raise_()
        JarvisUI.setCentralWidget(self.JarvisUi)

        self.retranslateUi(JarvisUI)
        QtCore.QMetaObject.connectSlotsByName(JarvisUI)

    def retranslateUi(self, JarvisUI):
        _translate = QtCore.QCoreApplication.translate
        JarvisUI.setWindowTitle(_translate("JarvisUI", "MainWindow"))
        self.StartButton.setText(_translate("JarvisUI", "start"))
        self.QuitButton.setText(_translate("JarvisUI", "start"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    JarvisUI = QtWidgets.QMainWindow()
    ui = Ui_JarvisUI()
    ui.setupUi(JarvisUI)
    JarvisUI.show()
    sys.exit(app.exec_())
